### ISSUE TITLE
Hello i have a question idk if you respond to this but

### ISSUE THREAD

**Issue by noaskers** [divios/Neptune-Framework#5]
You made a plugin called DailyShop a while ago not sure what happend or you lost motivation but the plugin don't work anymore

Please add me on discord:
NoAskers

If you need help I can help you.

**Comment by divios** [comment]
Hi,

I am currently undertaking a complete overhaul of Dailyshop, starting from scratch. This framework is part of it, and my intention is to develop and share it as open-source with the community, as it holds great value. 

Unfortunately, due to my busy schedule in the real world, I am uncertain when I will be able to complete Dailyshop.

**Comment by noaskers** [comment]
Alright thanks for this infomration

TIP: also tell people this on your spigot page cus the people could know now the reviews are flooded with bad info

**Comment by noaskers** [comment]
And even to there are some bugs here & there could you mabye just update it so the plugins works on 1.20.1 even to its has some bugs or will that not work?
